-- =====================================================================
-- M2 — Catálogo real del cliente, generado por scripts/migrar-excel.ts
-- Fuente: PRINCIPAL Auto inventario diario.xlsx · Generado: 2026-07-07
-- Reemplaza los datos de prueba de supabase/seed.sql.
-- =====================================================================

begin;

-- Limpieza de datos de prueba (ninguna sucursal ha capturado datos reales)
delete from reglas_sugerido;
delete from movimientos_diarios;
delete from cierres_dia;
delete from productos;
delete from departamentos;

-- Departamentos (una sección del Excel = un departamento)
insert into departamentos (nombre) values
  ('VAINILLA'),
  ('CHOCOLATE'),
  ('MIXTO'),
  ('PASTELES VARIOS'),
  ('QUEQUITOS'),
  ('TORTAS'),
  ('REPOSTERIA'),
  ('REPOSTERIA DE PAN'),
  ('PIES'),
  ('VARIOS'),
  ('PANES'),
  ('GALLETAS'),
  ('SALADO'),
  ('FRIO VAINILLA'),
  ('FRIO CHOCOLATE'),
  ('REPOSTERIA FRIA'),
  ('ESPECIALES');

-- Productos
insert into productos (nombre, categoria, tamano, departamento_id, lleva_decoracion) values
  ('VAINILLA', 'VAINILLA', '6X2', (select id from departamentos where nombre = 'VAINILLA'), true),
  ('VAINILLA', 'VAINILLA', '8X2', (select id from departamentos where nombre = 'VAINILLA'), true),
  ('VAINILLA', 'VAINILLA', '9X2', (select id from departamentos where nombre = 'VAINILLA'), true),
  ('VAINILLA', 'VAINILLA', '10X2', (select id from departamentos where nombre = 'VAINILLA'), true),
  ('VAINILLA', 'VAINILLA', '11X2', (select id from departamentos where nombre = 'VAINILLA'), true),
  ('VAINILLA', 'VAINILLA', '9X13X2', (select id from departamentos where nombre = 'VAINILLA'), true),
  ('Porciones VAINILLA', 'VAINILLA', null, (select id from departamentos where nombre = 'VAINILLA'), false),
  ('CHOCOLATE', 'CHOCOLATE', '6X2', (select id from departamentos where nombre = 'CHOCOLATE'), true),
  ('CHOCOLATE', 'CHOCOLATE', '8X2', (select id from departamentos where nombre = 'CHOCOLATE'), true),
  ('CHOCOLATE', 'CHOCOLATE', '10X2', (select id from departamentos where nombre = 'CHOCOLATE'), true),
  ('Porciones CHOCOLATE', 'CHOCOLATE', null, (select id from departamentos where nombre = 'CHOCOLATE'), false),
  ('MIXTO', 'MIXTO', '6X2', (select id from departamentos where nombre = 'MIXTO'), true),
  ('MIXTO', 'MIXTO', '8X2', (select id from departamentos where nombre = 'MIXTO'), true),
  ('MIXTO', 'MIXTO', '10X2', (select id from departamentos where nombre = 'MIXTO'), true),
  ('Porciones MIXTO', 'MIXTO', null, (select id from departamentos where nombre = 'MIXTO'), false),
  ('ZANAHORIA 10X2', 'PASTELES VARIOS', null, (select id from departamentos where nombre = 'PASTELES VARIOS'), true),
  ('DULCE DE LECHE CHOCOLATE 6', 'PASTELES VARIOS', null, (select id from departamentos where nombre = 'PASTELES VARIOS'), true),
  ('Porciones de pastel de 8', 'PASTELES VARIOS', null, (select id from departamentos where nombre = 'PASTELES VARIOS'), false),
  ('ZANAHORIA 8X2', 'PASTELES VARIOS', null, (select id from departamentos where nombre = 'PASTELES VARIOS'), true),
  ('ZANAHORIA 6', 'PASTELES VARIOS', null, (select id from departamentos where nombre = 'PASTELES VARIOS'), true),
  ('Porciones ZANAHORIA 6', 'PASTELES VARIOS', null, (select id from departamentos where nombre = 'PASTELES VARIOS'), false),
  ('ALMENDRA', 'PASTELES VARIOS', null, (select id from departamentos where nombre = 'PASTELES VARIOS'), true),
  ('Porciones ALMENDRA', 'PASTELES VARIOS', null, (select id from departamentos where nombre = 'PASTELES VARIOS'), false),
  ('MARMOLEADO', 'PASTELES VARIOS', null, (select id from departamentos where nombre = 'PASTELES VARIOS'), true),
  ('Porciones MARMOLEADO', 'PASTELES VARIOS', null, (select id from departamentos where nombre = 'PASTELES VARIOS'), false),
  ('TERCIOPELO ROJO 8', 'PASTELES VARIOS', null, (select id from departamentos where nombre = 'PASTELES VARIOS'), true),
  ('TERCIOPELO ROJO 6', 'PASTELES VARIOS', null, (select id from departamentos where nombre = 'PASTELES VARIOS'), true),
  ('Porciones TERCIOPELO ROJO 6', 'PASTELES VARIOS', null, (select id from departamentos where nombre = 'PASTELES VARIOS'), false),
  ('VOLTEADO 8', 'PASTELES VARIOS', null, (select id from departamentos where nombre = 'PASTELES VARIOS'), true),
  ('DULCE DE LECHE CHOCOLATE 10', 'PASTELES VARIOS', null, (select id from departamentos where nombre = 'PASTELES VARIOS'), true),
  ('INDIVIDUALES 4X2', 'QUEQUITOS', null, (select id from departamentos where nombre = 'QUEQUITOS'), false),
  ('VAINILLA /LUSTRE (6)', 'QUEQUITOS', null, (select id from departamentos where nombre = 'QUEQUITOS'), false),
  ('INDIVIDUALES CHOCOLATE', 'QUEQUITOS', null, (select id from departamentos where nombre = 'QUEQUITOS'), false),
  ('VAINILLA SIN LUSTRE', 'QUEQUITOS', null, (select id from departamentos where nombre = 'QUEQUITOS'), false),
  ('CHOCOLATE CON LUSTRE (6)', 'QUEQUITOS', null, (select id from departamentos where nombre = 'QUEQUITOS'), false),
  ('RED VELVET(6)', 'QUEQUITOS', null, (select id from departamentos where nombre = 'QUEQUITOS'), false),
  ('QUESADILLA INDIVIDUAL', 'QUEQUITOS', null, (select id from departamentos where nombre = 'QUEQUITOS'), false),
  ('PIE DE MANZANA', 'QUEQUITOS', null, (select id from departamentos where nombre = 'QUEQUITOS'), false),
  ('PIE DE POLLO', 'QUEQUITOS', null, (select id from departamentos where nombre = 'QUEQUITOS'), false),
  ('GLASEADO DE NUEZ', 'QUEQUITOS', null, (select id from departamentos where nombre = 'QUEQUITOS'), false),
  ('MARQUESOTE', 'TORTAS', null, (select id from departamentos where nombre = 'TORTAS'), false),
  ('Porciones MARQUESOTE', 'TORTAS', null, (select id from departamentos where nombre = 'TORTAS'), false),
  ('TORTA PC', 'TORTAS', null, (select id from departamentos where nombre = 'TORTAS'), false),
  ('Porciones TORTA PC', 'TORTAS', null, (select id from departamentos where nombre = 'TORTAS'), false),
  ('MARGARINA', 'TORTAS', null, (select id from departamentos where nombre = 'TORTAS'), false),
  ('Porciones MARGARINA', 'TORTAS', null, (select id from departamentos where nombre = 'TORTAS'), false),
  ('MINI MARGARINA', 'TORTAS', null, (select id from departamentos where nombre = 'TORTAS'), false),
  ('ELOTE 9 pulgadas', 'REPOSTERIA', null, (select id from departamentos where nombre = 'REPOSTERIA'), false),
  ('Porciones ELOTE 9 pulgadas', 'REPOSTERIA', null, (select id from departamentos where nombre = 'REPOSTERIA'), false),
  ('DULCE LECHE CHOCOLATE 8', 'REPOSTERIA', null, (select id from departamentos where nombre = 'REPOSTERIA'), false),
  ('ESPUMILLA PALETA', 'REPOSTERIA', null, (select id from departamentos where nombre = 'REPOSTERIA'), false),
  ('BROWNIE', 'REPOSTERIA', null, (select id from departamentos where nombre = 'REPOSTERIA'), false),
  ('BRAZO GITANO', 'REPOSTERIA', null, (select id from departamentos where nombre = 'REPOSTERIA'), false),
  ('GLASEADO DE NUEZ Porciones', 'REPOSTERIA', null, (select id from departamentos where nombre = 'REPOSTERIA'), false),
  ('DANESAS', 'REPOSTERIA', null, (select id from departamentos where nombre = 'REPOSTERIA'), false),
  ('PUDIN DE QUEQUE', 'REPOSTERIA', null, (select id from departamentos where nombre = 'REPOSTERIA'), false),
  ('Porciones PUDIN DE QUEQUE', 'REPOSTERIA', null, (select id from departamentos where nombre = 'REPOSTERIA'), false),
  ('ALBOROTOS (RICE KRISPIES)', 'REPOSTERIA', null, (select id from departamentos where nombre = 'REPOSTERIA'), false),
  ('TWINKIE', 'REPOSTERIA', null, (select id from departamentos where nombre = 'REPOSTERIA'), false),
  ('MINICAKE ALMENDRA /PASA', 'REPOSTERIA', null, (select id from departamentos where nombre = 'REPOSTERIA'), false),
  ('PIE MANZANA DIETA', 'REPOSTERIA', null, (select id from departamentos where nombre = 'REPOSTERIA'), false),
  ('ESPUMILLAS', 'REPOSTERIA', null, (select id from departamentos where nombre = 'REPOSTERIA'), false),
  ('TRENZAS', 'REPOSTERIA DE PAN', null, (select id from departamentos where nombre = 'REPOSTERIA DE PAN'), false),
  ('FRUTA CRISTALIZADA', 'REPOSTERIA DE PAN', null, (select id from departamentos where nombre = 'REPOSTERIA DE PAN'), false),
  ('ENCANELADO 1', 'REPOSTERIA DE PAN', null, (select id from departamentos where nombre = 'REPOSTERIA DE PAN'), false),
  ('QUESADILLA ARROZ PORCION', 'REPOSTERIA DE PAN', null, (select id from departamentos where nombre = 'REPOSTERIA DE PAN'), false),
  ('GLASEADO COCO', 'REPOSTERIA DE PAN', null, (select id from departamentos where nombre = 'REPOSTERIA DE PAN'), false),
  ('TARTALETAS FRUTA', 'REPOSTERIA DE PAN', null, (select id from departamentos where nombre = 'REPOSTERIA DE PAN'), false),
  ('BANANO', 'REPOSTERIA DE PAN', null, (select id from departamentos where nombre = 'REPOSTERIA DE PAN'), false),
  ('NUEZ', 'PIES', null, (select id from departamentos where nombre = 'PIES'), false),
  ('Porciones NUEZ', 'PIES', null, (select id from departamentos where nombre = 'PIES'), false),
  ('DURAZNO', 'PIES', null, (select id from departamentos where nombre = 'PIES'), false),
  ('Porciones DURAZNO', 'PIES', null, (select id from departamentos where nombre = 'PIES'), false),
  ('PIÑA', 'PIES', null, (select id from departamentos where nombre = 'PIES'), false),
  ('Porciones PIÑA', 'PIES', null, (select id from departamentos where nombre = 'PIES'), false),
  ('LECHE', 'PIES', null, (select id from departamentos where nombre = 'PIES'), false),
  ('Porciones LECHE', 'PIES', null, (select id from departamentos where nombre = 'PIES'), false),
  ('LIMON', 'PIES', null, (select id from departamentos where nombre = 'PIES'), false),
  ('Porciones LIMON', 'PIES', null, (select id from departamentos where nombre = 'PIES'), false),
  ('CHEESECAKE GR', 'PIES', null, (select id from departamentos where nombre = 'PIES'), false),
  ('Porciones CHEESECAKE GR', 'PIES', null, (select id from departamentos where nombre = 'PIES'), false),
  ('CHEESECAKE---- PEQ', 'PIES', null, (select id from departamentos where nombre = 'PIES'), false),
  ('GALLETAS AJONJOJI', 'VARIOS', null, (select id from departamentos where nombre = 'VARIOS'), false),
  ('GALLETAS COCO', 'VARIOS', null, (select id from departamentos where nombre = 'VARIOS'), false),
  ('QUEQUITOS CHEESECAKE FRESA', 'VARIOS', null, (select id from departamentos where nombre = 'VARIOS'), false),
  ('QUEQUITOS CHEESECAKE OREO', 'VARIOS', null, (select id from departamentos where nombre = 'VARIOS'), false),
  ('QUEQUITO CHEESECAKE DULCE LECHE', 'PANES', null, (select id from departamentos where nombre = 'PANES'), false),
  ('CROISSANT PAN', 'PANES', null, (select id from departamentos where nombre = 'PANES'), false),
  ('ARROZ', 'GALLETAS', null, (select id from departamentos where nombre = 'GALLETAS'), false),
  ('CORTAR', 'GALLETAS', null, (select id from departamentos where nombre = 'GALLETAS'), false),
  ('MANTEQUILLA/PASA', 'GALLETAS', null, (select id from departamentos where nombre = 'GALLETAS'), false),
  ('CREMA', 'GALLETAS', null, (select id from departamentos where nombre = 'GALLETAS'), false),
  ('MIGA/CHOCO', 'GALLETAS', null, (select id from departamentos where nombre = 'GALLETAS'), false),
  ('DECORADAS', 'GALLETAS', null, (select id from departamentos where nombre = 'GALLETAS'), false),
  ('PASTELITOS PIÑA', 'GALLETAS', null, (select id from departamentos where nombre = 'GALLETAS'), false),
  ('PASTELITOS CARNE', 'SALADO', null, (select id from departamentos where nombre = 'SALADO'), false),
  ('PASTELITOS POLLO', 'SALADO', null, (select id from departamentos where nombre = 'SALADO'), false),
  ('MICKEYS', 'SALADO', null, (select id from departamentos where nombre = 'SALADO'), false),
  ('CROISSANDWICH', 'SALADO', null, (select id from departamentos where nombre = 'SALADO'), false),
  ('BISCOCHOS', 'SALADO', null, (select id from departamentos where nombre = 'SALADO'), false),
  ('SANDWICH POLLO', 'SALADO', null, (select id from departamentos where nombre = 'SALADO'), false),
  ('SANDWICH POLLO DIETA', 'SALADO', null, (select id from departamentos where nombre = 'SALADO'), false),
  ('SANDWICH JAMON Y QUESO', 'SALADO', null, (select id from departamentos where nombre = 'SALADO'), false),
  ('3 LECHES 9 PULGADAS', 'FRIO VAINILLA', null, (select id from departamentos where nombre = 'FRIO VAINILLA'), false),
  ('Porciones 3 LECHES 9 PULGADAS', 'FRIO VAINILLA', null, (select id from departamentos where nombre = 'FRIO VAINILLA'), false),
  ('CHOCOALEMAN 8', 'FRIO VAINILLA', null, (select id from departamentos where nombre = 'FRIO VAINILLA'), false),
  ('CHOCOALEMAN 6', 'FRIO VAINILLA', null, (select id from departamentos where nombre = 'FRIO VAINILLA'), false),
  ('COOKIES AND CREAM 8', 'FRIO VAINILLA', null, (select id from departamentos where nombre = 'FRIO VAINILLA'), false),
  ('COOKIES AND CREAM 6', 'FRIO VAINILLA', null, (select id from departamentos where nombre = 'FRIO VAINILLA'), false),
  ('TIRAMISU GRD', 'FRIO VAINILLA', null, (select id from departamentos where nombre = 'FRIO VAINILLA'), false),
  ('TIRAMISU PEQ', 'FRIO VAINILLA', null, (select id from departamentos where nombre = 'FRIO VAINILLA'), false),
  ('ECLIPSE 8', 'FRIO VAINILLA', null, (select id from departamentos where nombre = 'FRIO VAINILLA'), false),
  ('ECLIPSE 6', 'FRIO VAINILLA', null, (select id from departamentos where nombre = 'FRIO VAINILLA'), false),
  ('CHOCOCREMA 8', 'FRIO CHOCOLATE', null, (select id from departamentos where nombre = 'FRIO CHOCOLATE'), false),
  ('CHOCOCREMA 6', 'FRIO CHOCOLATE', null, (select id from departamentos where nombre = 'FRIO CHOCOLATE'), false),
  ('Porciones CHOCOCREMA 6', 'FRIO CHOCOLATE', null, (select id from departamentos where nombre = 'FRIO CHOCOLATE'), false),
  ('SELVA NEGRA 8', 'FRIO CHOCOLATE', null, (select id from departamentos where nombre = 'FRIO CHOCOLATE'), false),
  ('SELVA NEGRA 6', 'FRIO CHOCOLATE', null, (select id from departamentos where nombre = 'FRIO CHOCOLATE'), false),
  ('Porciones SELVA NEGRA 6', 'FRIO CHOCOLATE', null, (select id from departamentos where nombre = 'FRIO CHOCOLATE'), false),
  ('CHOCOALMENDRA 8', 'FRIO CHOCOLATE', null, (select id from departamentos where nombre = 'FRIO CHOCOLATE'), false),
  ('CHOCOALMENDRA 6', 'FRIO CHOCOLATE', null, (select id from departamentos where nombre = 'FRIO CHOCOLATE'), false),
  ('Porciones CHOCOALMENDRA 6', 'FRIO CHOCOLATE', null, (select id from departamentos where nombre = 'FRIO CHOCOLATE'), false),
  ('PROFITEROLES', 'REPOSTERIA FRIA', null, (select id from departamentos where nombre = 'REPOSTERIA FRIA'), false),
  ('RELAMPAGOS', 'REPOSTERIA FRIA', null, (select id from departamentos where nombre = 'REPOSTERIA FRIA'), false),
  ('FLAN VAINILLA MEDIANO', 'REPOSTERIA FRIA', null, (select id from departamentos where nombre = 'REPOSTERIA FRIA'), false),
  ('FLAN VAINILLA COPA', 'REPOSTERIA FRIA', null, (select id from departamentos where nombre = 'REPOSTERIA FRIA'), false),
  ('FLAN COCO MEDIANO', 'REPOSTERIA FRIA', null, (select id from departamentos where nombre = 'REPOSTERIA FRIA'), false),
  ('FLAN COCO COPA', 'REPOSTERIA FRIA', null, (select id from departamentos where nombre = 'REPOSTERIA FRIA'), false),
  ('COPENHAGUE GRANDE', 'ESPECIALES', null, (select id from departamentos where nombre = 'ESPECIALES'), false),
  ('COPENHAGUE PEQUEÑO', 'ESPECIALES', null, (select id from departamentos where nombre = 'ESPECIALES'), false),
  ('SUSPIROS', 'ESPECIALES', null, (select id from departamentos where nombre = 'ESPECIALES'), false),
  ('CHOCOFLAN PORCIONES', 'ESPECIALES', null, (select id from departamentos where nombre = 'ESPECIALES'), false),
  ('CHOCOFLAN', 'ESPECIALES', null, (select id from departamentos where nombre = 'ESPECIALES'), false);

-- Reglas de sugeridos (dia_semana: 0=domingo … 6=sábado; null = todos los días)
insert into reglas_sugerido (producto_id, sucursal_id, dia_semana, objetivo)
select p.id, s.id, v.dia_semana, v.objetivo
from (values
  ('VAINILLA', '6X2', 'Cypress', null::smallint, 12),
  ('VAINILLA', '6X2', 'Chalets', 2, 4),
  ('VAINILLA', '6X2', 'Chalets', 3, 4),
  ('VAINILLA', '6X2', 'Chalets', 4, 4),
  ('VAINILLA', '6X2', 'Chalets', 5, 2),
  ('VAINILLA', '6X2', 'Chalets', 6, 2),
  ('VAINILLA', '6X2', 'Chalets', 0, 2),
  ('VAINILLA', '6X2', 'Chalets', 1, 2),
  ('VAINILLA', '6X2', 'Century', 2, 4),
  ('VAINILLA', '6X2', 'Century', 3, 4),
  ('VAINILLA', '6X2', 'Century', 4, 4),
  ('VAINILLA', '6X2', 'Century', 5, 3),
  ('VAINILLA', '6X2', 'Century', 6, 3),
  ('VAINILLA', '6X2', 'Century', 0, 3),
  ('VAINILLA', '6X2', 'Century', 1, 3),
  ('VAINILLA', '6X2', 'Altara', null, 5),
  ('VAINILLA', '6X2', 'Principal', null, 50),
  ('VAINILLA', '6X2', 'Palenque', 1, 8),
  ('VAINILLA', '6X2', 'Palenque', 2, 8),
  ('VAINILLA', '6X2', 'Palenque', 3, 8),
  ('VAINILLA', '6X2', 'Palenque', 4, 8),
  ('VAINILLA', '6X2', 'Palenque', 5, 8),
  ('VAINILLA', '6X2', 'Palenque', 6, 12),
  ('VAINILLA', '6X2', 'Palenque', 0, 12),
  ('VAINILLA', '8X2', 'Cypress', null, 12),
  ('VAINILLA', '8X2', 'Chalets', 2, 4),
  ('VAINILLA', '8X2', 'Chalets', 3, 4),
  ('VAINILLA', '8X2', 'Chalets', 4, 4),
  ('VAINILLA', '8X2', 'Chalets', 5, 2),
  ('VAINILLA', '8X2', 'Chalets', 6, 2),
  ('VAINILLA', '8X2', 'Chalets', 0, 2),
  ('VAINILLA', '8X2', 'Chalets', 1, 2),
  ('VAINILLA', '8X2', 'Century', 2, 6),
  ('VAINILLA', '8X2', 'Century', 3, 6),
  ('VAINILLA', '8X2', 'Century', 4, 6),
  ('VAINILLA', '8X2', 'Century', 5, 8),
  ('VAINILLA', '8X2', 'Century', 6, 8),
  ('VAINILLA', '8X2', 'Century', 0, 8),
  ('VAINILLA', '8X2', 'Century', 1, 8),
  ('VAINILLA', '8X2', 'Altara', null, 5),
  ('VAINILLA', '8X2', 'Principal', null, 50),
  ('VAINILLA', '8X2', 'Palenque', 1, 6),
  ('VAINILLA', '8X2', 'Palenque', 2, 6),
  ('VAINILLA', '8X2', 'Palenque', 3, 6),
  ('VAINILLA', '8X2', 'Palenque', 4, 6),
  ('VAINILLA', '8X2', 'Palenque', 5, 6),
  ('VAINILLA', '8X2', 'Palenque', 6, 12),
  ('VAINILLA', '8X2', 'Palenque', 0, 12),
  ('VAINILLA', '9X2', 'Cypress', null, 12),
  ('VAINILLA', '9X2', 'Chalets', 2, 2),
  ('VAINILLA', '9X2', 'Chalets', 3, 2),
  ('VAINILLA', '9X2', 'Chalets', 4, 2),
  ('VAINILLA', '9X2', 'Chalets', 5, 2),
  ('VAINILLA', '9X2', 'Chalets', 6, 2),
  ('VAINILLA', '9X2', 'Chalets', 0, 2),
  ('VAINILLA', '9X2', 'Chalets', 1, 2),
  ('VAINILLA', '9X2', 'Century', 2, 6),
  ('VAINILLA', '9X2', 'Century', 3, 6),
  ('VAINILLA', '9X2', 'Century', 4, 6),
  ('VAINILLA', '9X2', 'Century', 5, 8),
  ('VAINILLA', '9X2', 'Century', 6, 8),
  ('VAINILLA', '9X2', 'Century', 0, 8),
  ('VAINILLA', '9X2', 'Century', 1, 8),
  ('VAINILLA', '9X2', 'Altara', null, 2),
  ('VAINILLA', '9X2', 'Principal', null, 40),
  ('VAINILLA', '9X2', 'Palenque', 1, 3),
  ('VAINILLA', '9X2', 'Palenque', 2, 3),
  ('VAINILLA', '9X2', 'Palenque', 3, 3),
  ('VAINILLA', '9X2', 'Palenque', 4, 3),
  ('VAINILLA', '9X2', 'Palenque', 5, 3),
  ('VAINILLA', '9X2', 'Palenque', 6, 3),
  ('VAINILLA', '9X2', 'Palenque', 0, 3),
  ('VAINILLA', '10X2', 'Cypress', null, 10),
  ('VAINILLA', '10X2', 'Chalets', 2, 2),
  ('VAINILLA', '10X2', 'Chalets', 3, 2),
  ('VAINILLA', '10X2', 'Chalets', 4, 2),
  ('VAINILLA', '10X2', 'Chalets', 5, 2),
  ('VAINILLA', '10X2', 'Chalets', 6, 2),
  ('VAINILLA', '10X2', 'Chalets', 0, 2),
  ('VAINILLA', '10X2', 'Chalets', 1, 2),
  ('VAINILLA', '10X2', 'Century', 2, 6),
  ('VAINILLA', '10X2', 'Century', 3, 6),
  ('VAINILLA', '10X2', 'Century', 4, 6),
  ('VAINILLA', '10X2', 'Century', 5, 8),
  ('VAINILLA', '10X2', 'Century', 6, 8),
  ('VAINILLA', '10X2', 'Century', 0, 8),
  ('VAINILLA', '10X2', 'Century', 1, 8),
  ('VAINILLA', '10X2', 'Altara', null, 2),
  ('VAINILLA', '10X2', 'Principal', null, 24),
  ('VAINILLA', '10X2', 'Palenque', 1, 2),
  ('VAINILLA', '10X2', 'Palenque', 2, 2),
  ('VAINILLA', '10X2', 'Palenque', 3, 2),
  ('VAINILLA', '10X2', 'Palenque', 4, 2),
  ('VAINILLA', '10X2', 'Palenque', 5, 2),
  ('VAINILLA', '10X2', 'Palenque', 6, 4),
  ('VAINILLA', '10X2', 'Palenque', 0, 4),
  ('VAINILLA', '11X2', 'Cypress', null, 6),
  ('VAINILLA', '11X2', 'Chalets', 2, 2),
  ('VAINILLA', '11X2', 'Chalets', 3, 2),
  ('VAINILLA', '11X2', 'Chalets', 4, 2),
  ('VAINILLA', '11X2', 'Chalets', 5, 2),
  ('VAINILLA', '11X2', 'Chalets', 6, 2),
  ('VAINILLA', '11X2', 'Chalets', 0, 2),
  ('VAINILLA', '11X2', 'Chalets', 1, 2),
  ('VAINILLA', '11X2', 'Century', 2, 6),
  ('VAINILLA', '11X2', 'Century', 3, 6),
  ('VAINILLA', '11X2', 'Century', 4, 6),
  ('VAINILLA', '11X2', 'Century', 5, 8),
  ('VAINILLA', '11X2', 'Century', 6, 8),
  ('VAINILLA', '11X2', 'Century', 0, 8),
  ('VAINILLA', '11X2', 'Century', 1, 8),
  ('VAINILLA', '11X2', 'Altara', null, 2),
  ('VAINILLA', '11X2', 'Principal', null, 24),
  ('VAINILLA', '11X2', 'Palenque', 1, 2),
  ('VAINILLA', '11X2', 'Palenque', 2, 2),
  ('VAINILLA', '11X2', 'Palenque', 3, 2),
  ('VAINILLA', '11X2', 'Palenque', 4, 2),
  ('VAINILLA', '11X2', 'Palenque', 5, 2),
  ('VAINILLA', '11X2', 'Palenque', 6, 3),
  ('VAINILLA', '11X2', 'Palenque', 0, 3),
  ('VAINILLA', '9X13X2', 'Cypress', null, 1),
  ('VAINILLA', '9X13X2', 'Principal', null, 6),
  ('Porciones VAINILLA', null, 'Cypress', null, 5),
  ('Porciones VAINILLA', null, 'Chalets', null, 10),
  ('Porciones VAINILLA', null, 'Century', null, 5),
  ('Porciones VAINILLA', null, 'Altara', null, 5),
  ('Porciones VAINILLA', null, 'Principal', null, 10),
  ('Porciones VAINILLA', null, 'Palenque', null, 5),
  ('CHOCOLATE', '6X2', 'Cypress', null, 2),
  ('CHOCOLATE', '6X2', 'Chalets', null, 1),
  ('CHOCOLATE', '6X2', 'Century', null, 1),
  ('CHOCOLATE', '6X2', 'Altara', null, 1),
  ('CHOCOLATE', '6X2', 'Principal', null, 10),
  ('CHOCOLATE', '6X2', 'Palenque', null, 1),
  ('CHOCOLATE', '8X2', 'Cypress', null, 2),
  ('CHOCOLATE', '8X2', 'Chalets', null, 1),
  ('CHOCOLATE', '8X2', 'Century', null, 2),
  ('CHOCOLATE', '8X2', 'Altara', null, 1),
  ('CHOCOLATE', '8X2', 'Principal', null, 10),
  ('CHOCOLATE', '8X2', 'Palenque', null, 1),
  ('CHOCOLATE', '10X2', 'Cypress', null, 1),
  ('CHOCOLATE', '10X2', 'Century', null, 1),
  ('CHOCOLATE', '10X2', 'Principal', null, 8),
  ('CHOCOLATE', '10X2', 'Palenque', null, 1),
  ('Porciones CHOCOLATE', null, 'Cypress', null, 5),
  ('Porciones CHOCOLATE', null, 'Chalets', null, 5),
  ('Porciones CHOCOLATE', null, 'Century', null, 5),
  ('Porciones CHOCOLATE', null, 'Altara', null, 5),
  ('Porciones CHOCOLATE', null, 'Principal', null, 10),
  ('Porciones CHOCOLATE', null, 'Palenque', null, 5),
  ('MIXTO', '6X2', 'Cypress', null, 2),
  ('MIXTO', '6X2', 'Chalets', null, 1),
  ('MIXTO', '6X2', 'Century', null, 1),
  ('MIXTO', '6X2', 'Altara', null, 1),
  ('MIXTO', '6X2', 'Principal', null, 10),
  ('MIXTO', '6X2', 'Palenque', null, 2),
  ('MIXTO', '8X2', 'Cypress', null, 2),
  ('MIXTO', '8X2', 'Chalets', null, 1),
  ('MIXTO', '8X2', 'Century', null, 1),
  ('MIXTO', '8X2', 'Altara', null, 1),
  ('MIXTO', '8X2', 'Principal', null, 10),
  ('MIXTO', '8X2', 'Palenque', null, 2),
  ('MIXTO', '10X2', 'Cypress', null, 1),
  ('MIXTO', '10X2', 'Century', null, 1),
  ('MIXTO', '10X2', 'Altara', null, 1),
  ('MIXTO', '10X2', 'Principal', null, 6),
  ('MIXTO', '10X2', 'Palenque', null, 1),
  ('Porciones MIXTO', null, 'Cypress', null, 10),
  ('Porciones MIXTO', null, 'Chalets', null, 5),
  ('Porciones MIXTO', null, 'Century', null, 5),
  ('Porciones MIXTO', null, 'Altara', null, 5),
  ('Porciones MIXTO', null, 'Principal', null, 10),
  ('Porciones MIXTO', null, 'Palenque', null, 5),
  ('ZANAHORIA 10X2', null, 'Cypress', null, 1),
  ('ZANAHORIA 10X2', null, 'Chalets', null, 1),
  ('ZANAHORIA 10X2', null, 'Century', null, 1),
  ('ZANAHORIA 10X2', null, 'Altara', null, 1),
  ('ZANAHORIA 10X2', null, 'Principal', null, 1),
  ('ZANAHORIA 10X2', null, 'Palenque', null, 1),
  ('DULCE DE LECHE CHOCOLATE 6', null, 'Cypress', null, 1),
  ('DULCE DE LECHE CHOCOLATE 6', null, 'Chalets', null, 1),
  ('DULCE DE LECHE CHOCOLATE 6', null, 'Century', null, 1),
  ('DULCE DE LECHE CHOCOLATE 6', null, 'Altara', null, 1),
  ('DULCE DE LECHE CHOCOLATE 6', null, 'Principal', null, 2),
  ('DULCE DE LECHE CHOCOLATE 6', null, 'Palenque', null, 1),
  ('Porciones de pastel de 8', null, 'Cypress', null, 5),
  ('Porciones de pastel de 8', null, 'Chalets', null, 5),
  ('Porciones de pastel de 8', null, 'Century', null, 5),
  ('Porciones de pastel de 8', null, 'Altara', null, 5),
  ('Porciones de pastel de 8', null, 'Principal', null, 10),
  ('Porciones de pastel de 8', null, 'Palenque', null, 5),
  ('ZANAHORIA 8X2', null, 'Cypress', null, 2),
  ('ZANAHORIA 8X2', null, 'Chalets', null, 1),
  ('ZANAHORIA 8X2', null, 'Century', null, 2),
  ('ZANAHORIA 8X2', null, 'Altara', 5, 1),
  ('ZANAHORIA 8X2', null, 'Altara', 6, 2),
  ('ZANAHORIA 8X2', null, 'Principal', null, 4),
  ('ZANAHORIA 8X2', null, 'Palenque', null, 2),
  ('ZANAHORIA 6', null, 'Cypress', null, 2),
  ('ZANAHORIA 6', null, 'Chalets', null, 1),
  ('ZANAHORIA 6', null, 'Century', null, 1),
  ('ZANAHORIA 6', null, 'Altara', 5, 1),
  ('ZANAHORIA 6', null, 'Altara', 6, 2),
  ('ZANAHORIA 6', null, 'Principal', null, 4),
  ('ZANAHORIA 6', null, 'Palenque', null, 2),
  ('Porciones ZANAHORIA 6', null, 'Cypress', null, 5),
  ('Porciones ZANAHORIA 6', null, 'Chalets', null, 10),
  ('Porciones ZANAHORIA 6', null, 'Century', null, 5),
  ('Porciones ZANAHORIA 6', null, 'Altara', null, 5),
  ('Porciones ZANAHORIA 6', null, 'Principal', null, 10),
  ('Porciones ZANAHORIA 6', null, 'Palenque', null, 5),
  ('ALMENDRA', null, 'Cypress', null, 1),
  ('ALMENDRA', null, 'Chalets', null, 1),
  ('ALMENDRA', null, 'Century', null, 1),
  ('ALMENDRA', null, 'Altara', null, 1),
  ('ALMENDRA', null, 'Principal', null, 2),
  ('ALMENDRA', null, 'Palenque', null, 1),
  ('Porciones ALMENDRA', null, 'Cypress', null, 5),
  ('Porciones ALMENDRA', null, 'Chalets', null, 5),
  ('Porciones ALMENDRA', null, 'Century', null, 5),
  ('Porciones ALMENDRA', null, 'Altara', null, 5),
  ('Porciones ALMENDRA', null, 'Principal', null, 10),
  ('Porciones ALMENDRA', null, 'Palenque', null, 5),
  ('MARMOLEADO', null, 'Cypress', null, 1),
  ('MARMOLEADO', null, 'Century', null, 1),
  ('MARMOLEADO', null, 'Altara', null, 1),
  ('MARMOLEADO', null, 'Principal', null, 2),
  ('MARMOLEADO', null, 'Palenque', null, 1),
  ('Porciones MARMOLEADO', null, 'Cypress', null, 5),
  ('Porciones MARMOLEADO', null, 'Century', null, 5),
  ('Porciones MARMOLEADO', null, 'Altara', null, 5),
  ('Porciones MARMOLEADO', null, 'Principal', null, 10),
  ('Porciones MARMOLEADO', null, 'Palenque', null, 5),
  ('TERCIOPELO ROJO 8', null, 'Cypress', null, 1),
  ('TERCIOPELO ROJO 8', null, 'Chalets', null, 1),
  ('TERCIOPELO ROJO 8', null, 'Century', null, 1),
  ('TERCIOPELO ROJO 8', null, 'Altara', null, 1),
  ('TERCIOPELO ROJO 8', null, 'Principal', null, 2),
  ('TERCIOPELO ROJO 8', null, 'Palenque', null, 1),
  ('TERCIOPELO ROJO 6', null, 'Cypress', null, 1),
  ('TERCIOPELO ROJO 6', null, 'Chalets', null, 1),
  ('TERCIOPELO ROJO 6', null, 'Century', null, 1),
  ('TERCIOPELO ROJO 6', null, 'Altara', null, 1),
  ('TERCIOPELO ROJO 6', null, 'Principal', null, 2),
  ('TERCIOPELO ROJO 6', null, 'Palenque', null, 1),
  ('Porciones TERCIOPELO ROJO 6', null, 'Cypress', null, 5),
  ('Porciones TERCIOPELO ROJO 6', null, 'Chalets', null, 5),
  ('Porciones TERCIOPELO ROJO 6', null, 'Century', null, 5),
  ('Porciones TERCIOPELO ROJO 6', null, 'Altara', null, 5),
  ('Porciones TERCIOPELO ROJO 6', null, 'Principal', null, 10),
  ('Porciones TERCIOPELO ROJO 6', null, 'Palenque', null, 5),
  ('VOLTEADO 8', null, 'Century', null, 1),
  ('VOLTEADO 8', null, 'Principal', null, 1),
  ('VOLTEADO 8', null, 'Palenque', null, 1),
  ('DULCE DE LECHE CHOCOLATE 10', null, 'Cypress', null, 1),
  ('DULCE DE LECHE CHOCOLATE 10', null, 'Century', null, 1),
  ('DULCE DE LECHE CHOCOLATE 10', null, 'Principal', null, 1),
  ('DULCE DE LECHE CHOCOLATE 10', null, 'Palenque', null, 1),
  ('INDIVIDUALES 4X2', null, 'Cypress', null, 6),
  ('INDIVIDUALES 4X2', null, 'Chalets', null, 4),
  ('INDIVIDUALES 4X2', null, 'Century', null, 6),
  ('INDIVIDUALES 4X2', null, 'Altara', null, 6),
  ('INDIVIDUALES 4X2', null, 'Principal', null, 12),
  ('INDIVIDUALES 4X2', null, 'Palenque', null, 6),
  ('VAINILLA /LUSTRE (6)', null, 'Cypress', null, 3),
  ('VAINILLA /LUSTRE (6)', null, 'Chalets', null, 2),
  ('VAINILLA /LUSTRE (6)', null, 'Century', null, 2),
  ('VAINILLA /LUSTRE (6)', null, 'Altara', 5, 2),
  ('VAINILLA /LUSTRE (6)', null, 'Altara', 6, 3),
  ('VAINILLA /LUSTRE (6)', null, 'Principal', null, 6),
  ('VAINILLA /LUSTRE (6)', null, 'Palenque', null, 2),
  ('INDIVIDUALES CHOCOLATE', null, 'Cypress', null, 2),
  ('INDIVIDUALES CHOCOLATE', null, 'Chalets', null, 2),
  ('INDIVIDUALES CHOCOLATE', null, 'Century', null, 2),
  ('INDIVIDUALES CHOCOLATE', null, 'Altara', null, 2),
  ('INDIVIDUALES CHOCOLATE', null, 'Principal', null, 6),
  ('INDIVIDUALES CHOCOLATE', null, 'Palenque', null, 1),
  ('VAINILLA SIN LUSTRE', null, 'Chalets', null, 12),
  ('VAINILLA SIN LUSTRE', null, 'Century', null, 6),
  ('VAINILLA SIN LUSTRE', null, 'Altara', null, 6),
  ('VAINILLA SIN LUSTRE', null, 'Principal', null, 12),
  ('VAINILLA SIN LUSTRE', null, 'Palenque', null, 6),
  ('CHOCOLATE CON LUSTRE (6)', null, 'Cypress', null, 2),
  ('CHOCOLATE CON LUSTRE (6)', null, 'Chalets', null, 2),
  ('CHOCOLATE CON LUSTRE (6)', null, 'Century', null, 2),
  ('CHOCOLATE CON LUSTRE (6)', null, 'Altara', 5, 1),
  ('CHOCOLATE CON LUSTRE (6)', null, 'Altara', 6, 2),
  ('CHOCOLATE CON LUSTRE (6)', null, 'Principal', null, 6),
  ('CHOCOLATE CON LUSTRE (6)', null, 'Palenque', null, 1),
  ('RED VELVET(6)', null, 'Cypress', null, 2),
  ('RED VELVET(6)', null, 'Chalets', null, 2),
  ('RED VELVET(6)', null, 'Century', null, 2),
  ('RED VELVET(6)', null, 'Altara', 5, 2),
  ('RED VELVET(6)', null, 'Altara', 6, 3),
  ('RED VELVET(6)', null, 'Principal', null, 4),
  ('RED VELVET(6)', null, 'Palenque', null, 1),
  ('QUESADILLA INDIVIDUAL', null, 'Chalets', null, 12),
  ('QUESADILLA INDIVIDUAL', null, 'Century', null, 4),
  ('QUESADILLA INDIVIDUAL', null, 'Principal', null, 14),
  ('QUESADILLA INDIVIDUAL', null, 'Palenque', null, 4),
  ('PIE DE MANZANA', null, 'Cypress', null, 2),
  ('PIE DE MANZANA', null, 'Century', null, 2),
  ('PIE DE MANZANA', null, 'Altara', null, 2),
  ('PIE DE MANZANA', null, 'Principal', null, 1),
  ('PIE DE POLLO', null, 'Cypress', null, 4),
  ('PIE DE POLLO', null, 'Chalets', null, 4),
  ('PIE DE POLLO', null, 'Century', null, 4),
  ('PIE DE POLLO', null, 'Altara', null, 4),
  ('PIE DE POLLO', null, 'Principal', null, 2),
  ('PIE DE POLLO', null, 'Palenque', null, 4),
  ('GLASEADO DE NUEZ', null, 'Cypress', null, 1),
  ('GLASEADO DE NUEZ', null, 'Chalets', null, 1),
  ('GLASEADO DE NUEZ', null, 'Century', null, 1),
  ('GLASEADO DE NUEZ', null, 'Altara', null, 1),
  ('GLASEADO DE NUEZ', null, 'Principal', null, 2),
  ('GLASEADO DE NUEZ', null, 'Palenque', null, 2),
  ('MARQUESOTE', null, 'Cypress', null, 2),
  ('MARQUESOTE', null, 'Chalets', null, 1),
  ('MARQUESOTE', null, 'Century', null, 1),
  ('MARQUESOTE', null, 'Altara', null, 1),
  ('MARQUESOTE', null, 'Principal', null, 6),
  ('MARQUESOTE', null, 'Palenque', null, 1),
  ('Porciones MARQUESOTE', null, 'Cypress', null, 10),
  ('Porciones MARQUESOTE', null, 'Chalets', null, 10),
  ('Porciones MARQUESOTE', null, 'Century', null, 10),
  ('Porciones MARQUESOTE', null, 'Altara', null, 10),
  ('Porciones MARQUESOTE', null, 'Principal', null, 10),
  ('Porciones MARQUESOTE', null, 'Palenque', null, 10),
  ('TORTA PC', null, 'Chalets', null, 1),
  ('TORTA PC', null, 'Century', null, 1),
  ('TORTA PC', null, 'Altara', null, 1),
  ('TORTA PC', null, 'Principal', null, 2),
  ('Porciones TORTA PC', null, 'Cypress', null, 5),
  ('Porciones TORTA PC', null, 'Century', null, 5),
  ('Porciones TORTA PC', null, 'Altara', null, 5),
  ('Porciones TORTA PC', null, 'Principal', null, 10),
  ('Porciones TORTA PC', null, 'Palenque', null, 5),
  ('MARGARINA', null, 'Cypress', null, 2),
  ('MARGARINA', null, 'Chalets', null, 1),
  ('MARGARINA', null, 'Century', null, 2),
  ('MARGARINA', null, 'Altara', null, 2),
  ('MARGARINA', null, 'Principal', null, 8),
  ('MARGARINA', null, 'Palenque', null, 2),
  ('Porciones MARGARINA', null, 'Cypress', null, 5),
  ('Porciones MARGARINA', null, 'Chalets', null, 10),
  ('Porciones MARGARINA', null, 'Century', null, 10),
  ('Porciones MARGARINA', null, 'Altara', null, 5),
  ('Porciones MARGARINA', null, 'Principal', null, 10),
  ('Porciones MARGARINA', null, 'Palenque', null, 5),
  ('MINI MARGARINA', null, 'Cypress', null, 4),
  ('MINI MARGARINA', null, 'Chalets', null, 10),
  ('MINI MARGARINA', null, 'Century', null, 4),
  ('MINI MARGARINA', null, 'Altara', null, 6),
  ('MINI MARGARINA', null, 'Principal', null, 12),
  ('MINI MARGARINA', null, 'Palenque', null, 4),
  ('ELOTE 9 pulgadas', null, 'Cypress', null, 2),
  ('ELOTE 9 pulgadas', null, 'Chalets', null, 2),
  ('ELOTE 9 pulgadas', null, 'Altara', null, 2),
  ('ELOTE 9 pulgadas', null, 'Principal', null, 8),
  ('ELOTE 9 pulgadas', null, 'Palenque', null, 2),
  ('Porciones ELOTE 9 pulgadas', null, 'Cypress', null, 4),
  ('Porciones ELOTE 9 pulgadas', null, 'Chalets', null, 8),
  ('Porciones ELOTE 9 pulgadas', null, 'Century', null, 8),
  ('Porciones ELOTE 9 pulgadas', null, 'Altara', null, 4),
  ('Porciones ELOTE 9 pulgadas', null, 'Principal', null, 8),
  ('Porciones ELOTE 9 pulgadas', null, 'Palenque', null, 4),
  ('DULCE LECHE CHOCOLATE 8', null, 'Cypress', null, 1),
  ('DULCE LECHE CHOCOLATE 8', null, 'Chalets', null, 1),
  ('DULCE LECHE CHOCOLATE 8', null, 'Century', null, 1),
  ('DULCE LECHE CHOCOLATE 8', null, 'Altara', null, 1),
  ('DULCE LECHE CHOCOLATE 8', null, 'Principal', null, 2),
  ('DULCE LECHE CHOCOLATE 8', null, 'Palenque', null, 1),
  ('BROWNIE', null, 'Cypress', null, 6),
  ('BROWNIE', null, 'Chalets', null, 8),
  ('BROWNIE', null, 'Century', null, 10),
  ('BROWNIE', null, 'Altara', null, 6),
  ('BROWNIE', null, 'Principal', null, 48),
  ('BROWNIE', null, 'Palenque', null, 6),
  ('BRAZO GITANO', null, 'Cypress', null, 1),
  ('BRAZO GITANO', null, 'Century', null, 1),
  ('BRAZO GITANO', null, 'Altara', null, 1),
  ('BRAZO GITANO', null, 'Principal', null, 2),
  ('GLASEADO DE NUEZ Porciones', null, 'Cypress', null, 5),
  ('GLASEADO DE NUEZ Porciones', null, 'Chalets', null, 5),
  ('GLASEADO DE NUEZ Porciones', null, 'Century', null, 5),
  ('GLASEADO DE NUEZ Porciones', null, 'Altara', null, 5),
  ('GLASEADO DE NUEZ Porciones', null, 'Principal', null, 10),
  ('DANESAS', null, 'Cypress', null, 3),
  ('DANESAS', null, 'Chalets', null, 4),
  ('DANESAS', null, 'Century', null, 2),
  ('DANESAS', null, 'Altara', null, 2),
  ('DANESAS', null, 'Principal', null, 60),
  ('DANESAS', null, 'Palenque', null, 4),
  ('PUDIN DE QUEQUE', null, 'Cypress', null, 1),
  ('PUDIN DE QUEQUE', null, 'Chalets', null, 1),
  ('PUDIN DE QUEQUE', null, 'Century', null, 1),
  ('PUDIN DE QUEQUE', null, 'Altara', null, 1),
  ('PUDIN DE QUEQUE', null, 'Principal', null, 6),
  ('PUDIN DE QUEQUE', null, 'Palenque', null, 1),
  ('Porciones PUDIN DE QUEQUE', null, 'Cypress', null, 4),
  ('Porciones PUDIN DE QUEQUE', null, 'Century', null, 4),
  ('Porciones PUDIN DE QUEQUE', null, 'Altara', null, 4),
  ('Porciones PUDIN DE QUEQUE', null, 'Principal', null, 6),
  ('Porciones PUDIN DE QUEQUE', null, 'Palenque', null, 4),
  ('ALBOROTOS (RICE KRISPIES)', null, 'Cypress', null, 6),
  ('ALBOROTOS (RICE KRISPIES)', null, 'Chalets', null, 6),
  ('ALBOROTOS (RICE KRISPIES)', null, 'Century', null, 6),
  ('ALBOROTOS (RICE KRISPIES)', null, 'Altara', null, 6),
  ('ALBOROTOS (RICE KRISPIES)', null, 'Principal', null, 15),
  ('ALBOROTOS (RICE KRISPIES)', null, 'Palenque', null, 6),
  ('TWINKIE', null, 'Cypress', null, 12),
  ('TWINKIE', null, 'Chalets', null, 4),
  ('TWINKIE', null, 'Century', null, 10),
  ('TWINKIE', null, 'Altara', null, 6),
  ('TWINKIE', null, 'Principal', null, 26),
  ('TWINKIE', null, 'Palenque', null, 6),
  ('MINICAKE ALMENDRA /PASA', null, 'Cypress', null, 4),
  ('MINICAKE ALMENDRA /PASA', null, 'Chalets', null, 10),
  ('MINICAKE ALMENDRA /PASA', null, 'Century', null, 4),
  ('MINICAKE ALMENDRA /PASA', null, 'Altara', null, 4),
  ('MINICAKE ALMENDRA /PASA', null, 'Principal', null, 12),
  ('MINICAKE ALMENDRA /PASA', null, 'Palenque', null, 4),
  ('PIE MANZANA DIETA', null, 'Cypress', null, 2),
  ('PIE MANZANA DIETA', null, 'Chalets', null, 4),
  ('PIE MANZANA DIETA', null, 'Century', null, 2),
  ('PIE MANZANA DIETA', null, 'Altara', null, 2),
  ('PIE MANZANA DIETA', null, 'Principal', null, 1),
  ('PIE MANZANA DIETA', null, 'Palenque', null, 2),
  ('ESPUMILLAS', null, 'Cypress', null, 20),
  ('ESPUMILLAS', null, 'Chalets', null, 24),
  ('ESPUMILLAS', null, 'Century', null, 12),
  ('ESPUMILLAS', null, 'Altara', null, 12),
  ('ESPUMILLAS', null, 'Principal', null, 80),
  ('ESPUMILLAS', null, 'Palenque', null, 12),
  ('TRENZAS', null, 'Chalets', null, 15),
  ('TRENZAS', null, 'Century', null, 4),
  ('TRENZAS', null, 'Altara', 5, 4),
  ('TRENZAS', null, 'Altara', 6, 6),
  ('TRENZAS', null, 'Principal', null, 45),
  ('TRENZAS', null, 'Palenque', null, 4),
  ('FRUTA CRISTALIZADA', null, 'Cypress', null, 1),
  ('FRUTA CRISTALIZADA', null, 'Chalets', null, 1),
  ('FRUTA CRISTALIZADA', null, 'Century', null, 1),
  ('FRUTA CRISTALIZADA', null, 'Altara', null, 1),
  ('FRUTA CRISTALIZADA', null, 'Principal', null, 50),
  ('FRUTA CRISTALIZADA', null, 'Palenque', null, 1),
  ('ENCANELADO 1', null, 'Cypress', null, 5),
  ('ENCANELADO 1', null, 'Chalets', null, 10),
  ('ENCANELADO 1', null, 'Century', null, 4),
  ('ENCANELADO 1', null, 'Altara', 5, 4),
  ('ENCANELADO 1', null, 'Altara', 6, 8),
  ('ENCANELADO 1', null, 'Principal', null, 54),
  ('ENCANELADO 1', null, 'Palenque', null, 4),
  ('QUESADILLA ARROZ PORCION', null, 'Chalets', null, 12),
  ('QUESADILLA ARROZ PORCION', null, 'Century', null, 4),
  ('QUESADILLA ARROZ PORCION', null, 'Altara', null, 4),
  ('QUESADILLA ARROZ PORCION', null, 'Principal', null, 24),
  ('QUESADILLA ARROZ PORCION', null, 'Palenque', null, 4),
  ('GLASEADO COCO', null, 'Cypress', null, 1),
  ('GLASEADO COCO', null, 'Chalets', null, 1),
  ('GLASEADO COCO', null, 'Century', null, 1),
  ('GLASEADO COCO', null, 'Altara', null, 1),
  ('GLASEADO COCO', null, 'Principal', null, 2),
  ('GLASEADO COCO', null, 'Palenque', null, 1),
  ('TARTALETAS FRUTA', null, 'Cypress', null, 6),
  ('TARTALETAS FRUTA', null, 'Chalets', null, 6),
  ('TARTALETAS FRUTA', null, 'Century', null, 6),
  ('TARTALETAS FRUTA', null, 'Altara', null, 6),
  ('TARTALETAS FRUTA', null, 'Principal', null, 6),
  ('TARTALETAS FRUTA', null, 'Palenque', null, 6),
  ('BANANO', null, 'Cypress', null, 4),
  ('BANANO', null, 'Chalets', null, 4),
  ('BANANO', null, 'Century', null, 4),
  ('BANANO', null, 'Altara', null, 4),
  ('BANANO', null, 'Principal', null, 4),
  ('NUEZ', null, 'Cypress', null, 1),
  ('NUEZ', null, 'Chalets', null, 1),
  ('NUEZ', null, 'Century', null, 1),
  ('NUEZ', null, 'Altara', null, 1),
  ('NUEZ', null, 'Principal', null, 2),
  ('NUEZ', null, 'Palenque', null, 1),
  ('Porciones NUEZ', null, 'Cypress', null, 4),
  ('Porciones NUEZ', null, 'Chalets', null, 8),
  ('Porciones NUEZ', null, 'Century', null, 4),
  ('Porciones NUEZ', null, 'Altara', null, 4),
  ('Porciones NUEZ', null, 'Principal', null, 8),
  ('Porciones NUEZ', null, 'Palenque', null, 4),
  ('DURAZNO', null, 'Principal', null, 1),
  ('Porciones DURAZNO', null, 'Century', null, 2),
  ('Porciones DURAZNO', null, 'Altara', null, 2),
  ('Porciones DURAZNO', null, 'Principal', null, 8),
  ('PIÑA', null, 'Principal', null, 1),
  ('Porciones PIÑA', null, 'Cypress', null, 4),
  ('Porciones PIÑA', null, 'Century', null, 2),
  ('Porciones PIÑA', null, 'Altara', null, 2),
  ('Porciones PIÑA', null, 'Principal', null, 8),
  ('LECHE', null, 'Cypress', null, 4),
  ('LECHE', null, 'Chalets', null, 1),
  ('LECHE', null, 'Century', null, 2),
  ('LECHE', null, 'Altara', null, 2),
  ('LECHE', null, 'Principal', null, 16),
  ('LECHE', null, 'Palenque', null, 2),
  ('Porciones LECHE', null, 'Cypress', null, 8),
  ('Porciones LECHE', null, 'Chalets', null, 8),
  ('Porciones LECHE', null, 'Century', null, 8),
  ('Porciones LECHE', null, 'Altara', null, 8),
  ('Porciones LECHE', null, 'Principal', null, 8),
  ('Porciones LECHE', null, 'Palenque', null, 8),
  ('LIMON', null, 'Cypress', null, 1),
  ('LIMON', null, 'Chalets', null, 1),
  ('LIMON', null, 'Century', null, 1),
  ('LIMON', null, 'Altara', null, 1),
  ('LIMON', null, 'Principal', null, 2),
  ('LIMON', null, 'Palenque', null, 1),
  ('Porciones LIMON', null, 'Cypress', null, 8),
  ('Porciones LIMON', null, 'Chalets', null, 8),
  ('Porciones LIMON', null, 'Century', null, 8),
  ('Porciones LIMON', null, 'Altara', null, 4),
  ('Porciones LIMON', null, 'Principal', null, 8),
  ('Porciones LIMON', null, 'Palenque', null, 4),
  ('CHEESECAKE GR', null, 'Cypress', null, 1),
  ('CHEESECAKE GR', null, 'Century', null, 1),
  ('CHEESECAKE GR', null, 'Altara', null, 1),
  ('CHEESECAKE GR', null, 'Principal', null, 8),
  ('CHEESECAKE GR', null, 'Palenque', null, 1),
  ('Porciones CHEESECAKE GR', null, 'Cypress', null, 8),
  ('Porciones CHEESECAKE GR', null, 'Chalets', null, 8),
  ('Porciones CHEESECAKE GR', null, 'Century', null, 8),
  ('Porciones CHEESECAKE GR', null, 'Altara', null, 4),
  ('Porciones CHEESECAKE GR', null, 'Principal', null, 8),
  ('Porciones CHEESECAKE GR', null, 'Palenque', null, 4),
  ('CHEESECAKE---- PEQ', null, 'Cypress', null, 1),
  ('CHEESECAKE---- PEQ', null, 'Chalets', null, 2),
  ('CHEESECAKE---- PEQ', null, 'Century', null, 1),
  ('CHEESECAKE---- PEQ', null, 'Altara', null, 1),
  ('CHEESECAKE---- PEQ', null, 'Principal', null, 8),
  ('CHEESECAKE---- PEQ', null, 'Palenque', null, 1),
  ('GALLETAS AJONJOJI', null, 'Cypress', null, 12),
  ('GALLETAS AJONJOJI', null, 'Chalets', null, 12),
  ('GALLETAS AJONJOJI', null, 'Century', null, 12),
  ('GALLETAS AJONJOJI', null, 'Altara', null, 12),
  ('GALLETAS AJONJOJI', null, 'Principal', null, 15),
  ('GALLETAS AJONJOJI', null, 'Palenque', null, 12),
  ('GALLETAS COCO', null, 'Cypress', null, 12),
  ('GALLETAS COCO', null, 'Chalets', null, 12),
  ('GALLETAS COCO', null, 'Century', null, 12),
  ('GALLETAS COCO', null, 'Altara', null, 12),
  ('GALLETAS COCO', null, 'Principal', null, 15),
  ('GALLETAS COCO', null, 'Palenque', null, 12),
  ('QUEQUITOS CHEESECAKE FRESA', null, 'Cypress', null, 5),
  ('QUEQUITOS CHEESECAKE FRESA', null, 'Chalets', null, 5),
  ('QUEQUITOS CHEESECAKE FRESA', null, 'Century', null, 5),
  ('QUEQUITOS CHEESECAKE FRESA', null, 'Altara', null, 5),
  ('QUEQUITOS CHEESECAKE FRESA', null, 'Principal', null, 5),
  ('QUEQUITOS CHEESECAKE FRESA', null, 'Palenque', null, 5),
  ('QUEQUITOS CHEESECAKE OREO', null, 'Cypress', null, 5),
  ('QUEQUITOS CHEESECAKE OREO', null, 'Chalets', null, 5),
  ('QUEQUITOS CHEESECAKE OREO', null, 'Century', null, 5),
  ('QUEQUITOS CHEESECAKE OREO', null, 'Altara', null, 5),
  ('QUEQUITOS CHEESECAKE OREO', null, 'Principal', null, 5),
  ('QUEQUITOS CHEESECAKE OREO', null, 'Palenque', null, 5),
  ('QUEQUITO CHEESECAKE DULCE LECHE', null, 'Cypress', null, 5),
  ('QUEQUITO CHEESECAKE DULCE LECHE', null, 'Chalets', null, 5),
  ('QUEQUITO CHEESECAKE DULCE LECHE', null, 'Century', null, 5),
  ('QUEQUITO CHEESECAKE DULCE LECHE', null, 'Altara', null, 5),
  ('QUEQUITO CHEESECAKE DULCE LECHE', null, 'Principal', null, 5),
  ('QUEQUITO CHEESECAKE DULCE LECHE', null, 'Palenque', null, 5),
  ('CROISSANT PAN', null, 'Principal', null, 36),
  ('CROISSANT PAN', null, 'Palenque', null, 2),
  ('ARROZ', null, 'Cypress', null, 24),
  ('ARROZ', null, 'Chalets', null, 15),
  ('ARROZ', null, 'Century', null, 24),
  ('ARROZ', null, 'Altara', null, 24),
  ('ARROZ', null, 'Principal', null, 44),
  ('ARROZ', null, 'Palenque', null, 12),
  ('CORTAR', null, 'Cypress', null, 24),
  ('CORTAR', null, 'Chalets', null, 15),
  ('CORTAR', null, 'Century', null, 24),
  ('CORTAR', null, 'Altara', null, 24),
  ('CORTAR', null, 'Principal', null, 64),
  ('CORTAR', null, 'Palenque', null, 12),
  ('MANTEQUILLA/PASA', null, 'Cypress', null, 24),
  ('MANTEQUILLA/PASA', null, 'Chalets', null, 15),
  ('MANTEQUILLA/PASA', null, 'Century', null, 24),
  ('MANTEQUILLA/PASA', null, 'Altara', null, 24),
  ('MANTEQUILLA/PASA', null, 'Principal', null, 64),
  ('MANTEQUILLA/PASA', null, 'Palenque', null, 12),
  ('CREMA', null, 'Cypress', null, 16),
  ('CREMA', null, 'Chalets', null, 10),
  ('CREMA', null, 'Century', null, 16),
  ('CREMA', null, 'Altara', null, 16),
  ('CREMA', null, 'Principal', null, 44),
  ('CREMA', null, 'Palenque', null, 12),
  ('MIGA/CHOCO', null, 'Cypress', null, 36),
  ('MIGA/CHOCO', null, 'Chalets', null, 36),
  ('MIGA/CHOCO', null, 'Century', null, 36),
  ('MIGA/CHOCO', null, 'Altara', null, 36),
  ('MIGA/CHOCO', null, 'Principal', null, 90),
  ('MIGA/CHOCO', null, 'Palenque', null, 36),
  ('DECORADAS', null, 'Cypress', null, 12),
  ('DECORADAS', null, 'Chalets', null, 12),
  ('DECORADAS', null, 'Century', null, 12),
  ('DECORADAS', null, 'Altara', null, 12),
  ('DECORADAS', null, 'Principal', null, 100),
  ('DECORADAS', null, 'Palenque', null, 12),
  ('PASTELITOS PIÑA', null, 'Cypress', null, 24),
  ('PASTELITOS PIÑA', null, 'Chalets', null, 24),
  ('PASTELITOS PIÑA', null, 'Century', null, 24),
  ('PASTELITOS PIÑA', null, 'Altara', null, 24),
  ('PASTELITOS PIÑA', null, 'Principal', null, 45),
  ('PASTELITOS PIÑA', null, 'Palenque', null, 24),
  ('PASTELITOS CARNE', null, 'Cypress', null, 30),
  ('PASTELITOS CARNE', null, 'Chalets', null, 60),
  ('PASTELITOS CARNE', null, 'Century', null, 30),
  ('PASTELITOS CARNE', null, 'Altara', 5, 25),
  ('PASTELITOS CARNE', null, 'Altara', 6, 40),
  ('PASTELITOS CARNE', null, 'Principal', null, 160),
  ('PASTELITOS CARNE', null, 'Palenque', null, 30),
  ('PASTELITOS POLLO', null, 'Cypress', null, 30),
  ('PASTELITOS POLLO', null, 'Chalets', null, 60),
  ('PASTELITOS POLLO', null, 'Century', null, 30),
  ('PASTELITOS POLLO', null, 'Altara', 5, 25),
  ('PASTELITOS POLLO', null, 'Altara', 6, 40),
  ('PASTELITOS POLLO', null, 'Principal', null, 160),
  ('PASTELITOS POLLO', null, 'Palenque', null, 30),
  ('MICKEYS', null, 'Cypress', null, 6),
  ('MICKEYS', null, 'Chalets', null, 24),
  ('MICKEYS', null, 'Century', null, 20),
  ('MICKEYS', null, 'Altara', null, 6),
  ('MICKEYS', null, 'Principal', null, 70),
  ('MICKEYS', null, 'Palenque', null, 20),
  ('CROISSANDWICH', null, 'Cypress', null, 3),
  ('CROISSANDWICH', null, 'Chalets', null, 12),
  ('CROISSANDWICH', null, 'Century', null, 4),
  ('CROISSANDWICH', null, 'Altara', null, 4),
  ('CROISSANDWICH', null, 'Principal', null, 36),
  ('CROISSANDWICH', null, 'Palenque', null, 4),
  ('BISCOCHOS', null, 'Principal', null, 18),
  ('SANDWICH POLLO', null, 'Cypress', null, 8),
  ('SANDWICH POLLO', null, 'Chalets', null, 12),
  ('SANDWICH POLLO', null, 'Century', null, 6),
  ('SANDWICH POLLO', null, 'Altara', 5, 4),
  ('SANDWICH POLLO', null, 'Altara', 6, 8),
  ('SANDWICH POLLO', null, 'Principal', null, 36),
  ('SANDWICH POLLO', null, 'Palenque', null, 6),
  ('SANDWICH POLLO DIETA', null, 'Century', null, 2),
  ('SANDWICH POLLO DIETA', null, 'Altara', null, 2),
  ('SANDWICH POLLO DIETA', null, 'Principal', null, 4),
  ('SANDWICH POLLO DIETA', null, 'Palenque', null, 2),
  ('SANDWICH JAMON Y QUESO', null, 'Cypress', null, 3),
  ('SANDWICH JAMON Y QUESO', null, 'Chalets', null, 10),
  ('SANDWICH JAMON Y QUESO', null, 'Century', null, 4),
  ('SANDWICH JAMON Y QUESO', null, 'Altara', 5, 4),
  ('SANDWICH JAMON Y QUESO', null, 'Altara', 6, 6),
  ('SANDWICH JAMON Y QUESO', null, 'Principal', null, 16),
  ('SANDWICH JAMON Y QUESO', null, 'Palenque', null, 4),
  ('3 LECHES 9 PULGADAS', null, 'Cypress', null, 1),
  ('3 LECHES 9 PULGADAS', null, 'Chalets', null, 1),
  ('3 LECHES 9 PULGADAS', null, 'Century', null, 1),
  ('3 LECHES 9 PULGADAS', null, 'Altara', null, 1),
  ('3 LECHES 9 PULGADAS', null, 'Principal', null, 6),
  ('3 LECHES 9 PULGADAS', null, 'Palenque', null, 1),
  ('Porciones 3 LECHES 9 PULGADAS', null, 'Cypress', null, 8),
  ('Porciones 3 LECHES 9 PULGADAS', null, 'Chalets', null, 4),
  ('Porciones 3 LECHES 9 PULGADAS', null, 'Century', null, 8),
  ('Porciones 3 LECHES 9 PULGADAS', null, 'Altara', null, 8),
  ('Porciones 3 LECHES 9 PULGADAS', null, 'Principal', null, 8),
  ('Porciones 3 LECHES 9 PULGADAS', null, 'Palenque', null, 8),
  ('CHOCOALEMAN 8', null, 'Cypress', null, 1),
  ('CHOCOALEMAN 8', null, 'Chalets', null, 1),
  ('CHOCOALEMAN 8', null, 'Century', null, 1),
  ('CHOCOALEMAN 8', null, 'Altara', null, 1),
  ('CHOCOALEMAN 8', null, 'Principal', null, 1),
  ('CHOCOALEMAN 8', null, 'Palenque', null, 1),
  ('CHOCOALEMAN 6', null, 'Cypress', null, 1),
  ('CHOCOALEMAN 6', null, 'Chalets', null, 1),
  ('CHOCOALEMAN 6', null, 'Century', null, 1),
  ('CHOCOALEMAN 6', null, 'Altara', null, 1),
  ('CHOCOALEMAN 6', null, 'Principal', null, 2),
  ('CHOCOALEMAN 6', null, 'Palenque', null, 1),
  ('COOKIES AND CREAM 8', null, 'Cypress', null, 1),
  ('COOKIES AND CREAM 8', null, 'Chalets', null, 1),
  ('COOKIES AND CREAM 8', null, 'Century', null, 1),
  ('COOKIES AND CREAM 8', null, 'Altara', null, 1),
  ('COOKIES AND CREAM 8', null, 'Principal', null, 2),
  ('COOKIES AND CREAM 8', null, 'Palenque', null, 1),
  ('COOKIES AND CREAM 6', null, 'Cypress', null, 1),
  ('COOKIES AND CREAM 6', null, 'Chalets', null, 1),
  ('COOKIES AND CREAM 6', null, 'Century', null, 1),
  ('COOKIES AND CREAM 6', null, 'Altara', null, 1),
  ('COOKIES AND CREAM 6', null, 'Principal', null, 2),
  ('COOKIES AND CREAM 6', null, 'Palenque', null, 1),
  ('TIRAMISU GRD', null, 'Principal', null, 1),
  ('TIRAMISU PEQ', null, 'Cypress', null, 1),
  ('TIRAMISU PEQ', null, 'Chalets', null, 1),
  ('TIRAMISU PEQ', null, 'Century', null, 1),
  ('TIRAMISU PEQ', null, 'Altara', null, 1),
  ('TIRAMISU PEQ', null, 'Principal', null, 2),
  ('TIRAMISU PEQ', null, 'Palenque', null, 1),
  ('ECLIPSE 8', null, 'Cypress', null, 1),
  ('ECLIPSE 8', null, 'Chalets', null, 1),
  ('ECLIPSE 8', null, 'Century', null, 1),
  ('ECLIPSE 8', null, 'Principal', null, 2),
  ('ECLIPSE 8', null, 'Palenque', null, 1),
  ('ECLIPSE 6', null, 'Cypress', null, 1),
  ('ECLIPSE 6', null, 'Chalets', null, 1),
  ('ECLIPSE 6', null, 'Century', null, 1),
  ('ECLIPSE 6', null, 'Altara', null, 1),
  ('ECLIPSE 6', null, 'Principal', null, 2),
  ('ECLIPSE 6', null, 'Palenque', null, 1),
  ('CHOCOCREMA 8', null, 'Cypress', null, 1),
  ('CHOCOCREMA 8', null, 'Chalets', null, 1),
  ('CHOCOCREMA 8', null, 'Century', null, 1),
  ('CHOCOCREMA 8', null, 'Altara', null, 1),
  ('CHOCOCREMA 8', null, 'Principal', null, 2),
  ('CHOCOCREMA 6', null, 'Cypress', null, 1),
  ('CHOCOCREMA 6', null, 'Chalets', null, 1),
  ('CHOCOCREMA 6', null, 'Century', null, 1),
  ('CHOCOCREMA 6', null, 'Altara', null, 1),
  ('CHOCOCREMA 6', null, 'Principal', null, 2),
  ('CHOCOCREMA 6', null, 'Palenque', null, 1),
  ('Porciones CHOCOCREMA 6', null, 'Cypress', null, 4),
  ('Porciones CHOCOCREMA 6', null, 'Chalets', null, 5),
  ('Porciones CHOCOCREMA 6', null, 'Century', null, 4),
  ('Porciones CHOCOCREMA 6', null, 'Altara', null, 4),
  ('Porciones CHOCOCREMA 6', null, 'Principal', null, 10),
  ('Porciones CHOCOCREMA 6', null, 'Palenque', null, 4),
  ('SELVA NEGRA 8', null, 'Cypress', null, 1),
  ('SELVA NEGRA 8', null, 'Principal', null, 2),
  ('SELVA NEGRA 6', null, 'Cypress', null, 1),
  ('SELVA NEGRA 6', null, 'Chalets', null, 1),
  ('SELVA NEGRA 6', null, 'Century', null, 1),
  ('SELVA NEGRA 6', null, 'Altara', null, 1),
  ('SELVA NEGRA 6', null, 'Principal', null, 2),
  ('SELVA NEGRA 6', null, 'Palenque', null, 1),
  ('Porciones SELVA NEGRA 6', null, 'Cypress', null, 4),
  ('Porciones SELVA NEGRA 6', null, 'Chalets', null, 5),
  ('Porciones SELVA NEGRA 6', null, 'Century', null, 4),
  ('Porciones SELVA NEGRA 6', null, 'Altara', null, 4),
  ('Porciones SELVA NEGRA 6', null, 'Principal', null, 10),
  ('Porciones SELVA NEGRA 6', null, 'Palenque', null, 4),
  ('CHOCOALMENDRA 8', null, 'Cypress', null, 1),
  ('CHOCOALMENDRA 8', null, 'Century', null, 1),
  ('CHOCOALMENDRA 8', null, 'Altara', null, 1),
  ('CHOCOALMENDRA 8', null, 'Principal', null, 2),
  ('CHOCOALMENDRA 6', null, 'Cypress', null, 1),
  ('CHOCOALMENDRA 6', null, 'Chalets', null, 1),
  ('CHOCOALMENDRA 6', null, 'Century', null, 1),
  ('CHOCOALMENDRA 6', null, 'Altara', null, 1),
  ('CHOCOALMENDRA 6', null, 'Principal', null, 2),
  ('CHOCOALMENDRA 6', null, 'Palenque', null, 1),
  ('Porciones CHOCOALMENDRA 6', null, 'Cypress', null, 4),
  ('Porciones CHOCOALMENDRA 6', null, 'Chalets', null, 5),
  ('Porciones CHOCOALMENDRA 6', null, 'Century', null, 4),
  ('Porciones CHOCOALMENDRA 6', null, 'Altara', null, 4),
  ('Porciones CHOCOALMENDRA 6', null, 'Principal', null, 10),
  ('Porciones CHOCOALMENDRA 6', null, 'Palenque', null, 4),
  ('PROFITEROLES', null, 'Cypress', null, 11),
  ('PROFITEROLES', null, 'Chalets', null, 6),
  ('PROFITEROLES', null, 'Century', null, 6),
  ('PROFITEROLES', null, 'Altara', 5, 5),
  ('PROFITEROLES', null, 'Altara', 6, 10),
  ('PROFITEROLES', null, 'Principal', null, 22),
  ('PROFITEROLES', null, 'Palenque', null, 2),
  ('RELAMPAGOS', null, 'Cypress', null, 11),
  ('RELAMPAGOS', null, 'Chalets', null, 6),
  ('RELAMPAGOS', null, 'Century', null, 6),
  ('RELAMPAGOS', null, 'Altara', 5, 5),
  ('RELAMPAGOS', null, 'Altara', 6, 10),
  ('RELAMPAGOS', null, 'Principal', null, 22),
  ('RELAMPAGOS', null, 'Palenque', null, 2),
  ('FLAN VAINILLA MEDIANO', null, 'Cypress', null, 1),
  ('FLAN VAINILLA MEDIANO', null, 'Principal', null, 2),
  ('FLAN VAINILLA MEDIANO', null, 'Palenque', null, 1),
  ('FLAN VAINILLA COPA', null, 'Cypress', null, 5),
  ('FLAN VAINILLA COPA', null, 'Chalets', null, 10),
  ('FLAN VAINILLA COPA', null, 'Century', null, 12),
  ('FLAN VAINILLA COPA', null, 'Altara', null, 12),
  ('FLAN VAINILLA COPA', null, 'Principal', null, 36),
  ('FLAN VAINILLA COPA', null, 'Palenque', null, 6),
  ('FLAN COCO MEDIANO', null, 'Cypress', null, 1),
  ('FLAN COCO MEDIANO', null, 'Principal', null, 2),
  ('FLAN COCO MEDIANO', null, 'Palenque', null, 1),
  ('FLAN COCO COPA', null, 'Cypress', null, 5),
  ('FLAN COCO COPA', null, 'Chalets', null, 10),
  ('FLAN COCO COPA', null, 'Century', null, 12),
  ('FLAN COCO COPA', null, 'Altara', null, 12),
  ('FLAN COCO COPA', null, 'Principal', null, 36),
  ('FLAN COCO COPA', null, 'Palenque', null, 6),
  ('COPENHAGUE GRANDE', null, 'Cypress', null, 4),
  ('COPENHAGUE GRANDE', null, 'Chalets', null, 6),
  ('COPENHAGUE GRANDE', null, 'Century', null, 4),
  ('COPENHAGUE GRANDE', null, 'Altara', null, 4),
  ('COPENHAGUE GRANDE', null, 'Principal', null, 20),
  ('COPENHAGUE GRANDE', null, 'Palenque', null, 4),
  ('COPENHAGUE PEQUEÑO', null, 'Cypress', null, 4),
  ('COPENHAGUE PEQUEÑO', null, 'Chalets', null, 6),
  ('COPENHAGUE PEQUEÑO', null, 'Century', null, 4),
  ('COPENHAGUE PEQUEÑO', null, 'Altara', null, 4),
  ('COPENHAGUE PEQUEÑO', null, 'Principal', null, 20),
  ('SUSPIROS', null, 'Cypress', null, 4),
  ('SUSPIROS', null, 'Chalets', null, 6),
  ('SUSPIROS', null, 'Century', null, 4),
  ('SUSPIROS', null, 'Altara', null, 4),
  ('SUSPIROS', null, 'Principal', null, 18),
  ('SUSPIROS', null, 'Palenque', null, 4),
  ('CHOCOFLAN PORCIONES', null, 'Cypress', null, 5),
  ('CHOCOFLAN PORCIONES', null, 'Chalets', null, 5),
  ('CHOCOFLAN PORCIONES', null, 'Century', null, 5),
  ('CHOCOFLAN PORCIONES', null, 'Altara', null, 5),
  ('CHOCOFLAN PORCIONES', null, 'Principal', null, 10),
  ('CHOCOFLAN PORCIONES', null, 'Palenque', null, 5),
  ('CHOCOFLAN', null, 'Cypress', null, 1),
  ('CHOCOFLAN', null, 'Chalets', null, 1),
  ('CHOCOFLAN', null, 'Century', null, 1),
  ('CHOCOFLAN', null, 'Altara', null, 1),
  ('CHOCOFLAN', null, 'Principal', null, 4),
  ('CHOCOFLAN', null, 'Palenque', null, 1)
) as v(nombre, tamano, sucursal, dia_semana, objetivo)
join productos p on p.nombre = v.nombre and p.tamano is not distinct from v.tamano
join sucursales s on s.nombre = v.sucursal;

commit;
